"""
Django settings for diplomproject project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import dj_database_url
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '03byi&18pd&a3p8*j8*ocu_00m+-m77_2u9a_6yfjnig08umx^'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False
DEBUG = True

ALLOWED_HOSTS = ['best-shop.herokuapp.com','localhost','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'diplomapp.apps.DiplomappConfig',
    'bootstrap4',
    'slugify',
    'mptt',
    'whitenoise',
    'django_extensions',
    'django_popup_view_field',
    'multiselectfield',
    'django.contrib.postgres',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'diplomproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'diplomapp.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'diplomproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.postgresql',
    'NAME': 'diplomapp',
    'USER': 'admin',
    'PASSWORD': 'v19551955',
    'HOST': 'localhost',
    }
}



#### Настройки для хер  оку
# DATABASES = {
#     'default': {
#     # 'ENGINE': 'django.db.backends.postgresql',
#     'HOST': 'ec2-54-246-89-234.eu-west-1.compute.amazonaws.com',
#     'DATABASE': 'd38l3vfj452lqt',
#     'USER': 'uakwnapvdbsxfz',
#     'PASSWORD': '74977923f915f3dc712b5cf6aaa1bf63b3a52f85b70cae07d6cec80d938edd74',
#     'URI':'postgres://uakwnapvdbsxfz:74977923f915f3dc712b5cf6aaa1bf63b3a52f85b70cae07d6cec80d938edd74@ec2-54-246-89-234.eu-west-1.compute.amazonaws.com:5432/d38l3vfj452lqt',
#     'PORT':'5432',
#     }
# }

# psql -U admin -h 127.0.0.1 diplomapp для входа в бд через консоль


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
LOGIN_REDIRECT_URL='/sitename/'
LOGOUT_REDIRECT_URL='/sitename/sign-in/'

MEDIA_URL='/media/'
#MEDIA_ROOT=os.path.join(BASE_DIR,'media')
MEDIA_ROOT=BASE_DIR+MEDIA_URL

#STATIC_ROOT=os.path.join(BASE_DIR,'staticfiles')
STATIC_ROOT=os.path.join(BASE_DIR,'static/')


# import psycopg2
# DATABASE_URL = os.environ['DATABASE_URL']
#conn = psycopg2.connect(DATABASE_URL, sslmode='require')
#DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True)

db_from_env=dj_database_url.config()
DATABASES['default'].update(db_from_env)


GRAPH_MODELS = {
  'all_applications': True,
  'group_models': True,
}

CART_SESSION_ID = 'diplomapp'
