# Generated by Django 3.0.5 on 2020-05-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
    ]
