# Generated by Django 3.0.5 on 2020-05-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0003_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shops_list',
            field=models.ManyToManyField(default=None, to='diplomapp.Shop', verbose_name='Список магазинов'),
        ),
    ]
