# Generated by Django 3.0.5 on 2020-05-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0004_order_shops_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shops_list',
        ),
    ]
