# Generated by Django 3.0.5 on 2020-05-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0005_remove_order_shops_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_list',
            field=models.ManyToManyField(default=None, to='diplomapp.Shop', verbose_name='Список магазинов'),
        ),
    ]
