# Generated by Django 3.0.5 on 2020-05-24 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0006_order_shop_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop_list',
        ),
    ]
