# Generated by Django 3.0.5 on 2020-05-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0007_remove_order_shop_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=0, max_length=30, verbose_name='Номер телефона'),
        ),
    ]
